## PHASE 3— drug_subtype_labels

In [19]:
# Step 1: Load required libraries
import pandas as pd
import numpy as np

In [25]:
import os
os.getcwd()

'C:\\Users\\deep8\\breast_cancer_project'

In [27]:
import os

os.listdir()

['.ipynb_checkpoints',
 'R_file 8.ipynb',
 'R_file1.ipynb',
 'R_file2.ipynb',
 'R_file3.ipynb',
 'R_file4.ipynb',
 'R_file5.ipynb',
 'R_file6.ipynb',
 'R_file7.ipynb',
 'Untitled.ipynb']

In [29]:
DATA_DIR = r"C:\Users\deep8\breast_cancer_project_folder"

In [33]:
os.listdir(DATA_DIR)

['.ipynb_checkpoints',
 'Census_allWed Jan 28 09_32_24 2026.csv',
 'chembl_36_chemreps.txt',
 'chembl_mechanism.json',
 'chembl_target.json',
 'chembl_uniprot_mapping.txt',
 'clinical.tsv',
 'CRISPR_gene_effect.csv',
 'DEGs_HER2_vs_Normal_FDR0.05_log2FC1.csv',
 'DEGs_LumA_vs_Normal_FDR0.05_log2FC1.csv',
 'DEGs_LumB_vs_Normal_FDR0.05_log2FC1.csv',
 'DEGs_TNBC_vs_Normal_FDR0.05_log2FC1.csv',
 'Drug_Clinical_Regulatory_Features.csv',
 'Drug_CRISPR_Essentiality_Global.csv',
 'Drug_CRISPR_Essentiality_HER2.csv',
 'Drug_CRISPR_Essentiality_Luminal.csv',
 'Drug_CRISPR_Essentiality_TNBC.csv',
 'Drug_HER2_MinShortestPath.csv',
 'Drug_HER2_Propagation_Overlap.csv',
 'Drug_LINCS_Connectivity_HER2.csv',
 'Drug_LINCS_Connectivity_LumA.csv',
 'Drug_LumA_Propagation_Overlap.csv',
 'Drug_LumA_RW_Proximity.csv',
 'Drug_LumA_ShortestPath.csv',
 'Drug_LumB_Propagation_Overlap.csv',
 'Drug_LumB_RW_Proximity.csv',
 'Drug_LumB_ShortestPath.csv',
 'Drug_Pathways.csv',
 'Drug_Pathway_Enrichment_Similarity_HER2.csv',
 'Drug_Pathway_Enrichment_Similarity_LumA.csv',
 'Drug_Pathway_Enrichment_Similarity_LumB.csv',
 'Drug_Pathway_Enrichment_Similarity_TNBC.csv',
 'Drug_Pathway_Features_HER2.csv',
 'Drug_Pathway_Features_HER2_FINAL.csv',
 'Drug_Pathway_Features_LumA.csv',
 'Drug_Pathway_Features_LumA_FINAL.csv',
 'Drug_Pathway_Features_LumB.csv',
 'Drug_Pathway_Features_LumB_FINAL.csv',
 'Drug_Pathway_Features_TNBC.csv',
 'Drug_Pathway_Features_TNBC_FINAL.csv',
 'Drug_Pathway_Overlap_HER2.csv',
 'Drug_Pathway_Overlap_LumA.csv',
 'Drug_Pathway_Overlap_LumB.csv',
 'Drug_Pathway_Overlap_TNBC.csv',
 'Drug_Protein_Family_Features_HER2.csv',
 'Drug_Protein_Family_Features_LumB.csv',
 'Drug_Protein_Family_Features_TNBC.csv',
 'Drug_RW_Proximity_HER2.csv',
 'Drug_Targets_PPI_Filtered.csv',
 'Drug_TNBC_Propagation.csv',
 'Drug_TNBC_RW_Features.csv',
 'exposure.tsv',
 'family_history.tsv',
 'features_all.csv',
 'follow_up.tsv',
 'gdc_manifest.2026-01-23.234051.txt',
 'Gene_Protein_Family.txt',
 'Heatmap_Top50_LumA_vs_Normal_ORDERED_600dpi.png',
 'HER2_Pathway_Scores.csv',
 'HER2_PPI_Pagerank.csv',
 'LINCS_Connectivity_LumB.csv',
 'LINCS_Connectivity_TNBC.csv',
 'LINCS_Drug_Signatures.csv',
 'LINCS_HER2_DOWN.txt',
 'LINCS_HER2_UP.txt',
 'LINCS_LumA_DOWN.txt',
 'LINCS_LumA_UP.txt',
 'LINCS_LumB_DOWN.txt',
 'LINCS_LumB_UP.txt',
 'LINCS_TNBC_DOWN.txt',
 'LINCS_TNBC_UP.txt',
 'LumA_Pathway_Scores.csv',
 'LumA_PPI_Pagerank.csv',
 'LumB_Pathway_Scores.csv',
 'LumB_PPI_Pagerank.csv',
 'MA_HER2_vs_Normal_600dpi.png',
 'MA_LumA_vs_Normal_600dpi.png',
 'MA_LumB_vs_Normal_600dpi.png',
 'MA_TNBC_vs_Normal_600dpi.png',
 'metadata.cart.2026-01-27.json',
 'metadata.json',
 'NCBI2Reactome_All_Levels.txt',
 'pathology_detail.tsv',
 'PPI_TCGA_BRCA_STRING_HQ.csv',
 'Reactome_HGNC_Mapping.csv',
 'sample_info.csv',
 'Seeds_HER2.csv',
 'Seeds_LumA.csv',
 'Seeds_LumB.csv',
 'Seeds_TNBC.csv',
 'TCGA.BRCA (2).sampleMap_BRCA_clinicalMatrix',
 'TCGA.BRCA.sampleMap_HiSeqV2.gz',
 'TCGA_BRCA_expr_PAM50_aligned.csv.gz',
 'TCGA_BRCA_PAM50_labels.csv',
 'TNBC_Pathway_Scores.csv',
 'TNBC_PPI_Pagerank.csv',
 'Untitled.ipynb',
 'Volcano_HER2_vs_Normal_600dpi.png',
 'Volcano_LumB_vs_Normal_UpDown_600dpi.png',
 'Volcano_TNBC_vs_Normal_600dpi.png']

In [35]:
features_all = pd.read_csv(
r"C:\Users\deep8\breast_cancer_project_folder\features_all.csv"
)

features_all.head()

,drug,n_pathways_luma,mean_pathway_score_luma,max_pathway_score_luma,sum_pathway_score_luma,n_pathways_lumb,mean_pathway_score_lumb,max_pathway_score_lumb,sum_pathway_score_lumb,n_pathways_her2,mean_pathway_score_her2,max_pathway_score_her2,sum_pathway_score_her2,n_pathways_tnbc,mean_pathway_score_tnbc,max_pathway_score_tnbc,sum_pathway_score_tnbc
0,CHEMBL1778,16,0.054038,0.153784,0.864616,16,0.000553,0.000623,0.008854,16,0.000545,0.000627,0.008726,16,0.000544,0.000618,0.008698
1,CHEMBL1782,5,0.015057,0.045174,0.075286,6,0.000444,0.000529,0.002664,5,0.000450,0.000511,0.002250,5,0.000443,0.000504,0.002214
2,CHEMBL1783,29,0.046635,0.153784,1.352424,29,0.000612,0.001022,0.017737,29,0.000606,0.001017,0.017570,29,0.000600,0.001012,0.017412
3,CHEMBL1785,10,0.041135,0.153784,0.411352,10,0.000487,0.000611,0.004873,10,0.000481,0.000591,0.004814,10,0.000482,0.000594,0.004819
4,CHEMBL1786,2,0.023320,0.045174,0.046641,2,0.000492,0.000494,0.000983,2,0.000490,0.000497,0.000979,2,0.000479,0.000479,0.000957

In [37]:
# Reshape pathway features to (drug × subtype) format

subtypes = ["luma", "lumb", "her2", "tnbc"]
long_dfs = []

for st in subtypes:
    cols = [c for c in features_all.columns if c.endswith(f"_{st}")]
    tmp = features_all[["drug"] + cols].copy()
    tmp.columns = ["drug"] + [c.replace(f"_{st}", "") for c in cols]
    tmp["subtype"] = st.upper()
    long_dfs.append(tmp)

pathway_long = pd.concat(long_dfs, ignore_index=True)
pathway_long.head()

,drug,n_pathways,mean_pathway_score,max_pathway_score,sum_pathway_score,subtype
0,CHEMBL1778,16,0.054038,0.153784,0.864616,LUMA
1,CHEMBL1782,5,0.015057,0.045174,0.075286,LUMA
2,CHEMBL1783,29,0.046635,0.153784,1.352424,LUMA
3,CHEMBL1785,10,0.041135,0.153784,0.411352,LUMA
4,CHEMBL1786,2,0.023320,0.045174,0.046641,LUMA

In [41]:
import pandas as pd

gdsc = pd.read_csv(
    r"C:\Users\deep8\breast_cancer_project_folder\PANCANCER_IC_Wed Feb  4 05_36_16 2026.csv"
)

print(gdsc.shape)
gdsc.head()

(243466, 13)

,Drug Name,Drug ID,Cell Line Name,Cosmic ID,TCGA Classification,Tissue,Tissue Sub-type,IC50,AUC,Max Conc,RMSE,Z score,Dataset Version
0,Camptothecin,1003,PFSK-1,683667,MB,nervous_system,medulloblastoma,-1.463887,0.930220,0.1,0.089052,0.433123,GDSC2
1,Camptothecin,1003,A673,684052,UNCLASSIFIED,soft_tissue,rhabdomyosarcoma,-4.869455,0.614970,0.1,0.111351,-1.421100,GDSC2
2,Camptothecin,1003,ES5,684057,UNCLASSIFIED,bone,ewings_sarcoma,-3.360586,0.791072,0.1,0.142855,-0.599569,GDSC2
3,Camptothecin,1003,ES7,684059,UNCLASSIFIED,bone,ewings_sarcoma,-5.044940,0.592660,0.1,0.135539,-1.516647,GDSC2
4,Camptothecin,1003,EW-11,684062,UNCLASSIFIED,bone,ewings_sarcoma,-3.741991,0.734047,0.1,0.128059,-0.807232,GDSC2

In [43]:

# Filter breast cancer cell lines
gdsc_breast = gdsc[gdsc["Tissue"].str.lower() == "breast"].copy()

print(gdsc_breast.shape)
gdsc_breast[["Drug Name", "Cell Line Name", "Tissue", "AUC"]].head()

(13471, 13)

       Drug Name Cell Line Name  Tissue       AUC
92  Camptothecin        HCC1954  breast  0.983262
93  Camptothecin        HCC1143  breast  0.969050
94  Camptothecin        HCC1187  breast  0.992326
95  Camptothecin        HCC1395  breast  0.861208
96  Camptothecin        HCC1599  breast  0.768404

In [49]:
! pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\deep8\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\deep8\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [55]:

conda install openpyxl -y

Retrieving notices: done
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\deep8\anaconda3\envs\bcancer

  added / updated specs:
    - openpyxl


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2025.12.2  |       haa95532_0         125 KB
    certifi-2026.01.04         |  py310haa95532_0         148 KB
    et_xmlfile-2.0.0           |  py310haa95532_0          30 KB
    openpyxl-3.1.5             |  py310h827c3e9_1         567 KB
    openssl-3.0.19             |       hbb43b14_0         6.9 MB
    ------------------------------------------------------------
                                           Total:         7.8 MB

The following NEW packages will be INSTALLED:

  et_xmlfile         pkgs/main/win-64::et_xmlfile-2.0.0-py310haa95532_0
  openpyxl           pkgs/main/win-64::openpyxl-3.1.5-py310h827c3e9_1

The following packages will be UPDATED:

  ca-certificates                      2025.11.4-haa95532_0 --> 2025.12.2-haa95532_0
  certifi                        2025.11.12-py310haa95532_0 --> 2026.01.04-py310haa95532_0
  openssl                                 3.0.18-h543e019_0 --> 3.0.19-hbb43b14_0



Downloading and Extracting Packages: ...working...
openssl-3.0.19       | 6.9 MB    |            |   0%

openpyxl-3.1.5       | 567 KB    |            |   0%


certifi-2026.01.04   | 148 KB    |            |   0%



ca-certificates-2025 | 125 KB    |            |   0%




et_xmlfile-2.0.0     | 30 KB     |            |   0%



ca-certificates-2025 | 125 KB    | #2         |  13%




et_xmlfile-2.0.0     | 30 KB     | #####3     |  53%

openpyxl-3.1.5       | 567 KB    | 2          |   3%
openssl-3.0.19       | 6.9 MB    |            |   0%


certifi-2026.01.04   | 148 KB    | #          |  11%




et_xmlfile-2.0.0     | 30 KB     | ########## | 100%



ca-certificates-2025 | 125 KB    | ########## | 100%


certifi-2026.01.04   | 148 KB    | ########## | 100%

openpyxl-3.1.5       | 567 KB    | ########1  |  82%
openssl-3.0.19       | 6.9 MB    | 4          |   5%

openpyxl-3.1.5       | 567 KB    | ########## | 100%
openssl-3.0.19       | 6.9 MB    | #3         |  13%



ca-certificates-2025 | 125 KB    | ########## | 100%



ca-certificates-2025 | 125 KB    | ########## | 100%
openssl-3.0.19       | 6.9 MB    | ##2        |  23%




et_xmlfile-2.0.0     | 30 KB     | ########## | 100%




et_xmlfile-2.0.0     | 30 KB     | ########## | 100%
openssl-3.0.19       | 6.9 MB    | ###3       |  33%


certifi-2026.01.04   | 148 KB    | ########## | 100%


certifi-2026.01.04   | 148 KB    | ########## | 100%
openssl-3.0.19       | 6.9 MB    | ####5      |  46%
openssl-3.0.19       | 6.9 MB    | #####9     |  60%
openssl-3.0.19       | 6.9 MB    | #######    |  71%
openssl-3.0.19       | 6.9 MB    | ########2  |  82%
openssl-3.0.19       | 6.9 MB    | #########5 |  95%
openssl-3.0.19       | 6.9 MB    | ########## | 100%

openpyxl-3.1.5       | 567 KB    | ########## | 100%
openssl-3.0.19       | 6.9 MB    | ########## | 100%















                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [57]:
import pandas as pd

cell_lines = pd.read_excel(
    r"C:\Users\deep8\breast_cancer_project_folder\Cell_Lines_Details.xlsx"
)

print(cell_lines.shape)
cell_lines.head()

(1002, 13)

C:\Users\deep8\anaconda3\envs\bcancer\lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

,Sample Name,COSMIC identifier,Whole Exome Sequencing (WES),Copy Number Alterations (CNA),Gene Expression,Methylation,Drug\nResponse,GDSC\nTissue descriptor 1,GDSC\nTissue\ndescriptor 2,Cancer Type\n(matching TCGA label),Microsatellite \ninstability Status (MSI),Screen Medium,Growth Properties
0,A253,906794.0,Y,Y,Y,Y,Y,aero_dig_tract,head and neck,NaN,MSS/MSI-L,D/F12,Adherent
1,BB30-HNC,753531.0,Y,Y,Y,Y,Y,aero_dig_tract,head and neck,HNSC,MSS/MSI-L,D/F12,Adherent
2,BB49-HNC,753532.0,Y,Y,Y,Y,Y,aero_dig_tract,head and neck,HNSC,MSS/MSI-L,D/F12,Adherent
3,BHY,753535.0,Y,Y,Y,Y,Y,aero_dig_tract,head and neck,HNSC,MSS/MSI-L,D/F12,Adherent
4,BICR10,1290724.0,Y,Y,Y,Y,Y,aero_dig_tract,head and neck,HNSC,MSS/MSI-L,D/F12,Adherent

In [59]:
## PHASE 3.1 — Code Cell (Subtype mapping)


# Keep only breast cancer cell lines
breast_cells = cell_lines[
    cell_lines["Cancer Type\n(matching TCGA label)"] == "BRCA"
].copy()

print(breast_cells.shape)
breast_cells[["Sample Name", "Cancer Type\n(matching TCGA label)"]].head()

(51, 13)

    Sample Name Cancer Type\n(matching TCGA label)
270       AU565                               BRCA
271       BT-20                               BRCA
272      BT-474                               BRCA
273      BT-483                               BRCA
274      BT-549                               BRCA

In [61]:
## Code Cell — Load & inspect drug annotation

import pandas as pd

drug_info = pd.read_csv(
    r"C:\Users\deep8\breast_cancer_project_folder\screened_compounds_rel_8.5.csv"
)

print(drug_info.shape)
drug_info.head()

(621, 6)

,DRUG_ID,SCREENING_SITE,DRUG_NAME,SYNONYMS,TARGET,TARGET_PATHWAY
0,1,MGH,Erlotinib,"Tarceva, RG-1415, CP-358774, OSI-774, Ro-50823...",EGFR,EGFR signaling
1,3,MGH,Rapamycin,"AY-22989, Sirolimus, WY-090217, Torisel, Rapamune",MTORC1,PI3K/MTOR signaling
2,5,MGH,Sunitinib,"Sutent, Sunitinib Malate, SU-11248","PDGFR, KIT, VEGFR, FLT3, RET, CSF1R",RTK signaling
3,6,MGH,PHA-665752,"PHA665752, PHA 665752",MET,RTK signaling
4,9,MGH,MG-132,"LLL cpd, MG 132, MG132","Proteasome, CAPN1",Protein stability and degradation

# Phase 3.1 — GDSC labels

In [64]:

# Keep only required columns from GDSC breast response
gdsc_br = gdsc_breast[[
    "Drug Name",
    "Cell Line Name",
    "AUC"
]].copy()

print(gdsc_br.shape)
gdsc_br.head()

(13471, 3)

       Drug Name Cell Line Name       AUC
92  Camptothecin        HCC1954  0.983262
93  Camptothecin        HCC1143  0.969050
94  Camptothecin        HCC1187  0.992326
95  Camptothecin        HCC1395  0.861208
96  Camptothecin        HCC1599  0.768404

In [66]:
# assign breast cancer subtypes to cell lines

In [68]:

# Curated breast cancer cell line subtype mapping (standard)

subtype_map = {
    # Luminal
    "MCF7": "LUMA",
    "T47D": "LUMA",
    "ZR-75-1": "LUMA",
    "BT-483": "LUMA",
    "BT-474": "LUMB",
    "HCC1428": "LUMB",

    # HER2+
    "AU565": "HER2",
    "SK-BR-3": "HER2",
    "HCC1954": "HER2",

    # TNBC
    "BT-20": "TNBC",
    "BT-549": "TNBC",
    "HCC1143": "TNBC",
    "HCC1187": "TNBC",
    "HCC1395": "TNBC",
    "HCC1599": "TNBC",
    "MDA-MB-231": "TNBC",
    "MDA-MB-468": "TNBC"
}

# Map subtypes
gdsc_br["subtype"] = gdsc_br["Cell Line Name"].map(subtype_map)

# Drop unmapped cell lines
gdsc_br = gdsc_br.dropna(subset=["subtype"])

print(gdsc_br["subtype"].value_counts())
gdsc_br.head()

subtype
TNBC    2070
LUMA     733
LUMB     570
HER2     569
Name: count, dtype: int64

       Drug Name Cell Line Name       AUC subtype
92  Camptothecin        HCC1954  0.983262    HER2
93  Camptothecin        HCC1143  0.969050    TNBC
94  Camptothecin        HCC1187  0.992326    TNBC
95  Camptothecin        HCC1395  0.861208    TNBC
96  Camptothecin        HCC1599  0.768404    TNBC

In [70]:
# **convert cell-line–level AUC → drug × subtype evidence**.


# Aggregate AUC to drug × subtype level
drug_subtype_auc = (
    gdsc_br
    .groupby(["Drug Name", "subtype"])["AUC"]
    .median()
    .reset_index()
)

print(drug_subtype_auc.shape)
drug_subtype_auc.head()

(1118, 3)

  Drug Name subtype       AUC
0    123138    HER2  0.972264
1    123138    LUMA  0.972759
2    123138    LUMB  0.962818
3    123138    TNBC  0.983129
4    123829    HER2  0.956998

In [72]:
# **AUC → binary labels** using your predefined rules.

'''
- AUC < **0.2** → **Sensitive (label = 1)**
- AUC > **0.8** → **Resistant (label = 0)**
- Else → **Uncertain (drop for now)**
'''

def auc_to_label(auc):
    if auc < 0.2:
        return 1
    elif auc > 0.8:
        return 0
    else:
        return np.nan  # uncertain

drug_subtype_auc["label"] = drug_subtype_auc["AUC"].apply(auc_to_label)

# Keep only confident labels
gdsc_labels = drug_subtype_auc.dropna(subset=["label"]).copy()

gdsc_labels["label"] = gdsc_labels["label"].astype(int)

print(gdsc_labels.shape)
gdsc_labels["label"].value_counts()

(1004, 4)

label
0    1003
1       1
Name: count, dtype: int64

In [74]:
## ✅ Using relaxed rule (Option B)

'''
- **label = 1 (sensitive)** → AUC < **0.5**
- **label = 0 (resistant)** → AUC > **0.8**
- Else → drop (uncertain)
'''


# Recompute labels with relaxed threshold
def auc_to_label_relaxed(auc):
    if auc < 0.5:
        return 1
    elif auc > 0.8:
        return 0
    else:
        return np.nan

drug_subtype_auc["label"] = drug_subtype_auc["AUC"].apply(auc_to_label_relaxed)

gdsc_labels = drug_subtype_auc.dropna(subset=["label"]).copy()
gdsc_labels["label"] = gdsc_labels["label"].astype(int)

print(gdsc_labels.shape)
gdsc_labels["label"].value_counts()

(1020, 4)

label
0    1003
1      17
Name: count, dtype: int64

In [78]:
### Add confidence & evidence source


gdsc_labels["confidence"] = "medium"
gdsc_labels["evidence"] = "GDSC"

gdsc_labels.head()

  Drug Name subtype       AUC  label confidence evidence
0    123138    HER2  0.972264      0     medium     GDSC
1    123138    LUMA  0.972759      0     medium     GDSC
2    123138    LUMB  0.962818      0     medium     GDSC
3    123138    TNBC  0.983129      0     medium     GDSC
4    123829    HER2  0.956998      0     medium     GDSC

In [ ]:
# 123138 = internal GDSC drug ID

In [84]:
# Clean drug annotation table
drug_info_clean = drug_info.rename(columns={
    "DRUG_NAME": "drug_name"
})

# Ensure consistent string format
gdsc_labels["drug_name"] = gdsc_labels["gdsc_drug_id"].astype(str).str.strip()
drug_info_clean["drug_name"] = drug_info_clean["drug_name"].astype(str).str.strip()

# Merge on drug name
gdsc_labels = gdsc_labels.merge(
    drug_info_clean[["drug_name", "TARGET_PATHWAY"]],
    on="drug_name",
    how="left"
)

gdsc_labels[["drug_name", "TARGET_PATHWAY"]].head()

  drug_name TARGET_PATHWAY
0    123138   Unclassified
1    123138   Unclassified
2    123138   Unclassified
3    123138   Unclassified
4    123829   Unclassified

In [88]:

# Inspect columns carefully
print("gdsc_labels columns:")
print(gdsc_labels.columns.tolist())

print("\ndrug_info columns:")
print(drug_info.columns.tolist())

gdsc_labels columns:
['gdsc_drug_id_numeric', 'subtype', 'AUC', 'label', 'confidence', 'evidence', 'drug_name_x', 'TARGET_PATHWAY_x', 'drug_name_y', 'TARGET_PATHWAY_y']

drug_info columns:
['DRUG_ID', 'SCREENING_SITE', 'DRUG_NAME', 'SYNONYMS', 'TARGET', 'TARGET_PATHWAY']

In [92]:
# REBUILD aggregation using correct identifier: Drug ID

gdsc_br_correct = gdsc_breast[[
    "Drug ID",
    "Cell Line Name",
    "AUC"
]].copy()

# Attach subtype again
gdsc_br_correct["subtype"] = gdsc_br_correct["Cell Line Name"].map(subtype_map)
gdsc_br_correct = gdsc_br_correct.dropna(subset=["subtype"])

# Aggregate properly
drug_subtype_auc = (
    gdsc_br_correct
    .groupby(["Drug ID", "subtype"])["AUC"]
    .median()
    .reset_index()
)

print(drug_subtype_auc.head())
print("Rows:", drug_subtype_auc.shape)

   Drug ID subtype       AUC
0     1003    HER2  0.910857
1     1003    LUMA  0.922866
2     1003    LUMB  0.979757
3     1003    TNBC  0.884295
4     1004    HER2  0.834563
Rows: (1154, 3)

In [94]:

# Apply relaxed GDSC labeling
def auc_to_label_relaxed(auc):
    if auc < 0.5:
        return 1
    elif auc > 0.8:
        return 0
    else:
        return np.nan

drug_subtype_auc["label"] = drug_subtype_auc["AUC"].apply(auc_to_label_relaxed)

gdsc_labels = drug_subtype_auc.dropna(subset=["label"]).copy()
gdsc_labels["label"] = gdsc_labels["label"].astype(int)
gdsc_labels["confidence"] = "medium"
gdsc_labels["evidence"] = "GDSC"

print(gdsc_labels.shape)
gdsc_labels["label"].value_counts()

(1050, 6)

label
0    1031
1      19
Name: count, dtype: int64

In [96]:

# Prepare drug annotation table (clean)
drug_info_clean = drug_info.rename(columns={
    "DRUG_ID": "Drug ID",
    "DRUG_NAME": "drug_name",
    "TARGET_PATHWAY": "target_pathway"
})

# Ensure Drug ID is numeric on both sides
gdsc_labels["Drug ID"] = pd.to_numeric(gdsc_labels["Drug ID"], errors="coerce")
drug_info_clean["Drug ID"] = pd.to_numeric(drug_info_clean["Drug ID"], errors="coerce")

# Merge using correct key
gdsc_labels_final = gdsc_labels.merge(
    drug_info_clean[["Drug ID", "drug_name", "target_pathway"]],
    on="Drug ID",
    how="left"
)

# Sanity check
print(gdsc_labels_final.head())
print("\nMissing drug names:", gdsc_labels_final["drug_name"].isna().sum())

   Drug ID subtype       AUC  label confidence evidence     drug_name  \
0     1003    HER2  0.910857      0     medium     GDSC  Camptothecin
1     1003    LUMA  0.922866      0     medium     GDSC  Camptothecin
2     1003    LUMB  0.979757      0     medium     GDSC  Camptothecin
3     1003    TNBC  0.884295      0     medium     GDSC  Camptothecin
4     1004    HER2  0.834563      0     medium     GDSC   Vinblastine

    target_pathway
0  DNA replication
1  DNA replication
2  DNA replication
3  DNA replication
4          Mitosis

Missing drug names: 6

In [98]:
gdsc_labels_final = gdsc_labels_final.dropna(subset=["drug_name"]).copy()
print(gdsc_labels_final.shape)

(1044, 8)

In [100]:
gdsc_labels_final.to_csv(
    r"C:\Users\deep8\breast_cancer_project_folder\phase3_gdsc_labels.csv",
    index=False
)

print("Phase 3.1 saved successfully.")

Phase 3.1 saved successfully.

## PHASE 3.2 — ClinicalTrials.gov

In [103]:
import pandas as pd

ct = pd.read_csv(
    r"C:\Users\deep8\breast_cancer_project_folder\ctg-studies.csv"
)

print(ct.shape)
ct.head()

(55, 16)

,NCT Number,Study Title,Study URL,Study Status,Brief Summary,Conditions,Interventions,Primary Outcome Measures,Secondary Outcome Measures,Sponsor,Collaborators,Sex,Age,Phases,Enrollment,Study Type
0,NCT01234402,Study of Icrucumab (IMC-18F1) or Ramucirumab D...,https://clinicaltrials.gov/study/NCT01234402,COMPLETED,"An open-label, multicenter, randomized, Phase ...",Breast Cancer,BIOLOGICAL: Ramucirumab DP|BIOLOGICAL: IMC-18F...,"Progression-Free Survival (PFS), PFS is define...","Overall Survival (OS), Overall survival is def...",Eli Lilly and Company,NaN,ALL,"ADULT, OLDER_ADULT",PHASE2,153,INTERVENTIONAL
1,NCT00775645,S0715: Acetyl-L-Carnitine in Preventing Neurop...,https://clinicaltrials.gov/study/NCT00775645,COMPLETED,RATIONALE: Acetyl-L-carnitine may prevent or l...,Breast Cancer|Chemotherapeutic Agent Toxicity|...,DIETARY_SUPPLEMENT: acetyl-L-carnitine hydroch...,12-week FACT-Taxane Neurotoxicity Model-adjust...,12-week FACT-Trial Outcome Index(TOI) Function...,SWOG Cancer Research Network,National Cancer Institute (NCI),FEMALE,"ADULT, OLDER_ADULT",PHASE3,437,INTERVENTIONAL
2,NCT00471276,Efficacy And Safety Of Sunitinib In Women With...,https://clinicaltrials.gov/study/NCT00471276,COMPLETED,Patients with advanced breast cancer to receiv...,Breast Neoplasms,DRUG: sunitinib,Number of Participants With Objective Response...,"Number of Participants With Clinical Benefit, ...",Pfizer,NaN,FEMALE,"ADULT, OLDER_ADULT",PHASE2,83,INTERVENTIONAL
3,NCT02756364,Sapanisertib in Combination With Fulvestrant i...,https://clinicaltrials.gov/study/NCT02756364,COMPLETED,The primary purpose of this study is to compar...,Breast Neoplasms,DRUG: Fulvestrant|DRUG: Sapanisertib,"Progression Free Survival (PFS), PFS was defin...","Overall Survival (OS), OS was defined as the t...","Calithera Biosciences, Inc",NaN,FEMALE,"ADULT, OLDER_ADULT",PHASE2,141,INTERVENTIONAL
4,NCT00438100,Capecitabine vs. S-1 in Unresectable or Recurr...,https://clinicaltrials.gov/study/NCT00438100,COMPLETED,To investigate and compare the efficacy and sa...,Breast Neoplasms,DRUG: Capecitabine|DRUG: S-1,"Progression Free Survival, The follow up perio...","Adverse Events, The follow up period will be t...",Japan Breast Cancer Research Network,NaN,FEMALE,"ADULT, OLDER_ADULT",PHASE2,142,INTERVENTIONAL

In [105]:
### Extract drugs from trials

# Extract drug names from Intervention column
ct_drugs = (
    ct[["NCT Number", "Interventions", "Phases", "Study Status", "Conditions"]]
    .dropna(subset=["Interventions"])
    .copy()
)

ct_drugs.head()

,NCT Number,Interventions,Phases,Study Status,Conditions
0,NCT01234402,BIOLOGICAL: Ramucirumab DP|BIOLOGICAL: IMC-18F...,PHASE2,COMPLETED,Breast Cancer
1,NCT00775645,DIETARY_SUPPLEMENT: acetyl-L-carnitine hydroch...,PHASE3,COMPLETED,Breast Cancer|Chemotherapeutic Agent Toxicity|...
2,NCT00471276,DRUG: sunitinib,PHASE2,COMPLETED,Breast Neoplasms
3,NCT02756364,DRUG: Fulvestrant|DRUG: Sapanisertib,PHASE2,COMPLETED,Breast Neoplasms
4,NCT00438100,DRUG: Capecitabine|DRUG: S-1,PHASE2,COMPLETED,Breast Neoplasms

In [107]:

import re

def extract_drugs(intervention_str):
    # Remove prefixes like DRUG:, BIOLOGICAL:, etc.
    parts = intervention_str.split("|")
    drugs = []
    for p in parts:
        p = re.sub(r"^[A-Z_ ]+:\s*", "", p)
        drugs.append(p.strip().lower())
    return drugs

ct_drugs["drug_list"] = ct_drugs["Interventions"].apply(extract_drugs)

ct_drugs[["Interventions", "drug_list"]].head()

,Interventions,drug_list
0,BIOLOGICAL: Ramucirumab DP|BIOLOGICAL: IMC-18F...,"[ramucirumab dp, imc-18f1, capecitabine]"
1,DIETARY_SUPPLEMENT: acetyl-L-carnitine hydroch...,"[acetyl-l-carnitine hydrochloride, placebo]"
2,DRUG: sunitinib,[sunitinib]
3,DRUG: Fulvestrant|DRUG: Sapanisertib,"[fulvestrant, sapanisertib]"
4,DRUG: Capecitabine|DRUG: S-1,"[capecitabine, s-1]"

In [109]:

# Detect subtype from Conditions text
def detect_subtype(cond):
    c = cond.lower()
    if "her2" in c:
        return "HER2"
    elif "triple negative" in c or "tnbc" in c:
        return "TNBC"
    elif "luminal" in c or "er+" in c or "estrogen receptor" in c:
        return "LUMA"
    else:
        return "PAN"  # non-specific breast cancer

ct_drugs["subtype"] = ct_drugs["Conditions"].apply(detect_subtype)

ct_drugs[["Conditions", "subtype"]].head()

                                          Conditions subtype
0                                      Breast Cancer     PAN
1  Breast Cancer|Chemotherapeutic Agent Toxicity|...     PAN
2                                   Breast Neoplasms     PAN
3                                   Breast Neoplasms     PAN
4                                   Breast Neoplasms     PAN

In [111]:

# Clinical label assignment
def clinical_label(row):
 if row["Study Status"] in ["COMPLETED", "ACTIVE, NOT RECRUITING", "RECRUITING"]:
     if row["Phases"] in ["PHASE2", "PHASE3"]:
         return 1
 return 0

ct_drugs["clinical_label"] = ct_drugs.apply(clinical_label, axis=1)

ct_drugs[["Phases", "Study Status", "clinical_label"]].value_counts()

Phases         Study Status           clinical_label
PHASE2         COMPLETED              1                 27
PHASE3         COMPLETED              1                 12
PHASE1|PHASE2  COMPLETED              0                  7
PHASE3         ACTIVE_NOT_RECRUITING  0                  5
PHASE2|PHASE3  COMPLETED              0                  2
PHASE1|PHASE2  ACTIVE_NOT_RECRUITING  0                  1
PHASE2         ACTIVE_NOT_RECRUITING  0                  1
Name: count, dtype: int64

In [113]:

### Explode drug lists (one drug per row)

ct_exploded = ct_drugs.explode("drug_list").copy()

# Keep relevant columns
ct_exploded = ct_exploded[[
    "NCT Number",
    "drug_list",
    "subtype",
    "clinical_label",
    "Phases",
    "Study Status"
]]

ct_exploded.rename(columns={"drug_list": "drug_name"}, inplace=True)

print(ct_exploded.shape)
ct_exploded.head()

(186, 6)

,NCT Number,drug_name,subtype,clinical_label,Phases,Study Status
0,NCT01234402,ramucirumab dp,PAN,1,PHASE2,COMPLETED
0,NCT01234402,imc-18f1,PAN,1,PHASE2,COMPLETED
0,NCT01234402,capecitabine,PAN,1,PHASE2,COMPLETED
1,NCT00775645,acetyl-l-carnitine hydrochloride,PAN,1,PHASE3,COMPLETED
1,NCT00775645,placebo,PAN,1,PHASE3,COMPLETED

In [115]:

### Normalize drug names & drop non-therapeutics

def clean_drug_name(name):
    name = name.lower()
    name = name.replace(" hydrochloride", "")
    name = name.replace(" dp", "")
    name = name.replace("-", " ")
    return name.strip()

ct_exploded["drug_name_clean"] = ct_exploded["drug_name"].apply(clean_drug_name)

# Remove placebo / supplements
remove_terms = ["placebo", "acetyl", "vitamin", "supplement"]
ct_exploded = ct_exploded[
    ~ct_exploded["drug_name_clean"].str.contains("|".join(remove_terms))
].copy()

print(ct_exploded.shape)
ct_exploded[["drug_name", "drug_name_clean"]].head()

(172, 7)

        drug_name drug_name_clean
0  ramucirumab dp     ramucirumab
0        imc-18f1        imc 18f1
0    capecitabine    capecitabine
2       sunitinib       sunitinib
3     fulvestrant     fulvestrant

In [117]:

### Normalize GDSC drug names 
gdsc_map = gdsc_labels_final[["Drug ID", "drug_name"]].drop_duplicates().copy()

def norm(name):
    return (
        name.lower()
            .replace("-", " ")
            .replace(" hydrochloride", "")
            .replace(" dp", "")
            .strip()
    )

gdsc_map["drug_name_norm"] = gdsc_map["drug_name"].apply(norm)

gdsc_map.head()

    Drug ID     drug_name drug_name_norm
0      1003  Camptothecin   camptothecin
4      1004   Vinblastine    vinblastine
8      1005     Cisplatin      cisplatin
12     1006    Cytarabine     cytarabine
16     1007     Docetaxel      docetaxel

In [121]:
print(ct_mapped.columns.tolist())

['NCT Number', 'drug_name_x', 'subtype', 'clinical_label', 'Phases', 'Study Status', 'drug_name_clean', 'Drug ID', 'drug_name_y', 'drug_name_norm', 'confidence']

In [123]:

# Final clinical evidence table (clean)
ct_mapped_final = ct_mapped[[
    "Drug ID",
    "drug_name_y",
    "subtype",
    "clinical_label",
    "confidence"
]].drop_duplicates()

# Rename for consistency
ct_mapped_final = ct_mapped_final.rename(columns={
    "drug_name_y": "drug_name"
})

print(ct_mapped_final.shape)
ct_mapped_final.head()

(31, 5)

   Drug ID    drug_name subtype  clinical_label confidence
0     1200  Fulvestrant     PAN               1     medium
1     1816  Fulvestrant     PAN               1     medium
2     1080   Paclitaxel    TNBC               0     medium
3     1190  Gemcitabine     PAN               0       high
4     1080   Paclitaxel     PAN               0       high

In [125]:
## PHASE 3 — FINAL MERGE (3.1 + 3.2)


# Copy to avoid accidental overwrite
gdsc = gdsc_labels_final.copy()
clinical = ct_mapped_final.copy()

gdsc.head(), clinical.head()

(   Drug ID subtype       AUC  label confidence evidence     drug_name  \
 0     1003    HER2  0.910857      0     medium     GDSC  Camptothecin
 1     1003    LUMA  0.922866      0     medium     GDSC  Camptothecin
 2     1003    LUMB  0.979757      0     medium     GDSC  Camptothecin
 3     1003    TNBC  0.884295      0     medium     GDSC  Camptothecin
 4     1004    HER2  0.834563      0     medium     GDSC   Vinblastine

     target_pathway
 0  DNA replication
 1  DNA replication
 2  DNA replication
 3  DNA replication
 4          Mitosis  ,
    Drug ID    drug_name subtype  clinical_label confidence
 0     1200  Fulvestrant     PAN               1     medium
 1     1816  Fulvestrant     PAN               1     medium
 2     1080   Paclitaxel    TNBC               0     medium
 3     1190  Gemcitabine     PAN               0       high
 4     1080   Paclitaxel     PAN               0       high)

In [131]:

# Correct PAN expansion
subtypes = ["LUMA", "LUMB", "HER2", "TNBC"]

# Separate PAN and non-PAN clinical evidence
clinical_pan = clinical[clinical["subtype"] == "PAN"].copy()
clinical_specific = clinical[clinical["subtype"] != "PAN"].copy()

# Expand PAN rows to all subtypes
pan_expanded = pd.concat(
    [clinical_pan.assign(subtype=st) for st in subtypes],
    ignore_index=True
)

# Combine expanded PAN + subtype-specific clinical evidence
clinical_all = pd.concat(
    [clinical_specific, pan_expanded],
    ignore_index=True
)

print(clinical_all.shape)
clinical_all.head()

(94, 5)

   Drug ID    drug_name subtype  clinical_label confidence
0     1080   Paclitaxel    TNBC               0     medium
1     1190  Gemcitabine    TNBC               1       high
2     2048  Vinorelbine    TNBC               1       high
3     1200  Fulvestrant    HER2               0     medium
4     1816  Fulvestrant    HER2               0     medium

In [139]:
print(final_labels.columns.tolist())

['Drug ID', 'subtype', 'AUC', 'label', 'confidence_gdsc', 'evidence', 'drug_name_gdsc', 'target_pathway', 'drug_name_clinical', 'clinical_label', 'confidence_clinical', 'final_label']

In [141]:


# Create final_confidence (clinical overrides GDSC)
final_labels["final_confidence"] = (
    final_labels["confidence_clinical"]
    .fillna(final_labels["confidence_gdsc"])
)

# Final clean table
final_labels_clean = final_labels[[
    "Drug ID",
    "drug_name_gdsc",
    "subtype",
    "final_label",
    "final_confidence"
]].rename(columns={
    "drug_name_gdsc": "drug_name"
})

print(final_labels_clean.shape)
final_labels_clean.head()

(1072, 5)

   Drug ID     drug_name subtype  final_label final_confidence
0     1003  Camptothecin    HER2            0           medium
1     1003  Camptothecin    LUMA            0           medium
2     1003  Camptothecin    LUMB            0           medium
3     1003  Camptothecin    TNBC            0           medium
4     1004   Vinblastine    HER2            0           medium

In [143]:
final_labels_clean.to_csv(
    r"C:\Users\deep8\breast_cancer_project_folder\drug_subtype_labels.csv",
    index=False
)
print("Phase 3 saved.")

Phase 3 saved.